

- hosts: localhost
  gather_facts: true
  tasks: 
    - debug:
        msg:
         - "Die OS Distribution ist: {{ansible_distribution}}"
         - "Der OS Name ist: {{ansible_system}}"
         - "Die OS Familie ist: {{ansible_os_family}}"

